project:
  type: website
  output-dir: C:/Users/hphung.stu/OneDrive - UBC/Documents/GitHub/My-E-portfolio

website:
  title: "Your E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Publications
      - text: Content & Deliverable
        menu:
          - href: content.qmd
            text: Capstone Project
          - href: thesis1.qmd
            text: Molten Salt Carbonate Electrolysis
          - href: thesis2.qmd
            text: Effect of Nanoparticles on TiO2
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

