---
title: "Analysis of Suitable Sanctuaries for Humpback Whales"
format: html
editor: visual
---

::: panel-tabset
## Background

Hawaii is an archipelago located in the central Pacific Ocean, approximately 3850 km from Californa, USA (World Atlas, n.d). Aside being a wonderful place for visitors, Hawaii archipelago is also home to Humpback Whales during the winter time. The whales swim from Alaska to Hawaii to mate, give birth, and nurture their calves (Hawaii Wildlife Fund, n.d). Recognized as one of the world's most vital humpback whale habitats, the Hawaiian Islands Humpback Whale National Marine Sanctuary was established in 1992 to safeguard humpback whales (Megaptera novaeangliae) and their habitat in Hawai‘i (Division of Aquatic Resources, n.d). However, there have been reports about collisions between whales and human activities and objects such as cruise ships, whale watching boats, and fishing boats. Therefore, government agencies are working to identify the most suitable and expansive areas to incorporate into the sanctuary.

In order to complete the tasks, suitability analysis and overlay analysis were performed. Suitability analysis is a process used to determine the suitability of an area for a particular use or purpose based on given weighted criteria (ESRI a, n.d). Overlay analysis is a common method used in suitability analysis, which combines multiple dataset to create a comprehensive assessment (ArcMap, n,d).

## Objectives

-   The main objectives of this task is to create areas of the 5 most suitable sanctuary for Humpback Whales in Hawaii based on the weighted suitability index.

## Data descriptions

-   The data is obtained from UBC-postgres database.The necessary dataset used in this task are whale species, regions in which the whales appear, human activities that affect the whales. 


## References

ArcMap. (n.d). Overlay analysis. https://desktop.arcgis.com/en/arcmap/latest/analyze/commonly-used-tools/overlay-analysis.htm

Division of Aquatic Resources. (n.d). Hawaiian Islands Humpback Whale National Marine Sanctuary (HIHWNMS). https://dlnr.hawaii.gov/dar/marine-managed-areas/hawaiian-islands-humpback-whale-national-marine-sanctuary-hihwnms/

ESRI. (n.d). Perform a suitability analysis. https://pro.arcgis.com/en/pro-app/latest/help/analysis/business-analyst/understanding-suitability-analysis.htm

Hawaii Wildlife Fund. (n.d). Humpback Whale. https://www.wildhawaii.org/wildlife/whales/

World Atlas. (n.d). Maps of Hawaii. https://www.worldatlas.com/maps/united-states/hawaii
:::





