---
title: "Analysis of Burn Severity and Vegetation Recovery at Prouton Lake, BC"
format: html
editor: visual
---

::: panel-tabset
## Background

The background of the Prouton Lake and fire severity

## Objectives

Content details go here.

## Data descriptions

Deliverables information goes here.
:::

## Running Code

To begin with, I loaded the necessary library used for this analysis task.

```{r, echo = TRUE, warning = FALSE, message = FALSE}
library(terra)
library(sf)
library(readr)
library(stringr)
library(lubridate)
library(dplyr)
library(tidyr)
library(ggplot2)
library(bfast)
```

Read the data files to investigate the data and extract the information about total area burned in 2017

```{r}
h_fire_ply_polygon <- st_read("C:/Users/hphung.stu/Downloads/GEM520/Labs/Lab8/lab8_finalDemonstrationOfRSkills-assign/data/PROT_HISTORICAL_FIRE_POLYS_SP/H_FIRE_PLY_polygon.shp")

# Extract the data for the year 2017
fire_2017 <- h_fire_ply_polygon %>% 
  filter(FIRE_YEAR == 2017)

# Number of fire
number_of_fire <- nrow(fire_2017)
print(number_of_fire)

# Total land area burned
total_area_burned <- sum(fire_2017$SIZE_HA)
print(total_area_burned)

# Top 3 largest fire in 2017
three_largest_fire <- fire_2017 %>%
  arrange(desc(SIZE_HA)) %>% 
  slice_head(n = 3) %>% 
  st_drop_geometry()

print(three_largest_fire)

```

```{r}

```
