---
title: "Resume"
---

# Education 

- <span style="color: red;"> **Master of Geomatics for Environmental Management (July, 2024 - current)**</span>
  
  **The University of British Columbia**
  
    Capstone Project: Detecting change of aboveground biomass using Landsat 9, GEDI, and their 
    combination in Kwahu South, Ghana.

- <span style="color: red;">**Master of Science (Technology) in Environmental Engineering (August, 2020 - July, 2023)**</span>
  
  **Tampere University**

    Thesis: Molten Carbonate Salt Electrolysis - Materials Selection, Experimental Design,
    and Carbon Production.

- <span style="color: red;">**Bachelor of Engineer in Energy and Environmental Engineering (August, 2015 - June, 2019)**</span>

  **Tampere University of Applied Sciences**
  
    Thesis: Effect if Graphene/Gold - nanoparticles composite on the photocatalytics 
    activity of Titan Dioxide.

# Work Experience
## Environmental Specialist (Internship)                      Hanoi, Vietnam
- **STI Vietnam (July, 2023 - September, 2023)**

    - Conducted research on carbon market and carbon trade in Vietnam as well as in   South-East Asia region.
    - Contributed to write the proposal for the project of LiDAR Image Processing using AI for Affordable Forest Carbon Credit Evaluation and Monitoring in Laos and Vietnam.
    - Website: https://stivina.com/

## Research Assistant                                        Tampere, Finland
- **Tampere University (February, 2022 - June, 2023)**
    
    - Researched on CO2 capture by molten salt electrolysis in Hydrogen and Carbon Value Chain (HYGCEL) project.
    - Designed and constructed laboratory scale system for experiment of molten salt electrolysis.
    - Successfully found a material that was not only cost-effective but also durable for the molten salt electrolysis process.
    - Managed to produce carbon nano-onion product as well as other tubular carbon products.
    - Read more: http://bit.ly/4gGXPvq

## CAD Designer Trainee                                      Tampere, Finland
- **Ramboll Finland Oy (May, 2021 - August, 2021)**

    - Participated in on-the-job training, working closely with supervisors and coworkers (team of 10 people) and asking appropriate quations.
    - Designed Pipe and Instrument Diagram (P&ID) for water and wastewater treament plant in AutoCAD and AutoCAD Plant 3D.
    - Sketched a pumping station, which included 3D designed and orthographic drawing in AutoCAD Plant 3D.
    - Website: https://www.ramboll.com/fi-fi



# Conferences & Talks

*Invited Talks*

-   If you've been invited to speak in a professional setting, list that here.

*Conference Presentations*

-   If the presentation was at a conference, list them here.

# Awards & Honors

-   List any scholarships, bursaries, etc.

# Teaching Assistantships

-   List any TA positions you may have held.

# Institutional Service

-   Volunteering etc.
