---
title: "Effect of Graphene/Gold - nanoparticles composite on the photocatalytics activity of TiO2"
format: html
editor: visual
---

## This is my Bachelor's Thesis at Tampere University of Applied Sciences

Titan dioxide (TiO~2~) is used in the enhanced oxidation method because of its ability in photocatalysis. It has shown its potential in the application of removal contaminant in the environment. However, the ability of disposing contaminant of
TiO2 is efficient only under a specific wavelength. Therefore, two methods have
been researched in order to increase the ability of TiO2 in photocatalysis under
UV ray and visible light. The first one is to add metal nanoparticles to the surface
of TiO2. The other one is to attach nanocarbon dots on TiO2. In this thesis work,
Graphene and gold nanoparticles were chosen as a support for the photocatalysis of TiO2.

The aim of this thesis is to research about the effect of Graphene/gold nanoparticles on the photocatalysis of TiO2. In addition, the ratio of gold and graphene
also affected to the ability of photocatalysis. Therefore, different samples with
various ratios were made to determine a necessary sample with a specific ratio.

The thesis topic is belonged to Vietnam Academy of Science and Technology.


## Mechanism of photocatalysis

When the surface of TiO2 is illuminated by light with energy level similar or higher than the bandgap energy ΔE~bg~,  the electrons in the valence band are stimulated and moved to the conduction band (Thiruvenkatachari et al., 2006). As the electrons have moved to the conduction band, there are several holes in the valence band, and these holes are positive charge (h+). The electrons in the conduction band are now negative charge (e-). In the valence band, there is a formation of OH* radical due to the oxidation of h+ and the water in the environment. In conduction band, O2- is formed by the reduction of e- and oxygen